image: docker:latest

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:  
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags: 
    - build-docker
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG